javax:
  sql:
    DataSource:
      bookDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://127.0.0.1:5432/distribuida
          user: postgres
          password: postgres